### ISSUE TITLE
회원가입 수락이 안됨

### ISSUE THREAD

**Issue by googoo81** [GSM-MSG/GAuth-FrontEnd#210]
### Describe

![스크린샷 2024-05-28 오전 8 42 41](https://github.com/GSM-MSG/GAuth-FrontEnd/assets/101445027/13475abd-c3dd-48e1-bb8f-02f064ae8a69)
로그인시 관리자가 수락하지 않은 유저입니다 라는 메세지가 출력되지 않습니다.

**Comment by pki071120** [comment]
<img width="1512" alt="스크린샷 2024-07-01 오후 5 47 28" src="https://github.com/GSM-MSG/GAuth-FrontEnd/assets/129853254/2f4a29c7-54c9-4584-9ff0-d4d6db68a9eb">

gauth사이트에 로그인 할때는 잘 작동이 되는데 혹시 다시한번 확인해 주실 수 있나요?
