### ISSUE TITLE
문서가 없어서 프로젝트에 적용하기 어렵네요

### ISSUE THREAD

**Issue by chanwoo00106** [GSM-MSG/GAUTH-frontend#6]
> 문서화가 안되어 있어서 개인 프로젝트에 적용을 할 수가 없네요
> 빠른 시일 내에 문서가 README 같은 곳에 올라왔으면 좋겠네요

**Comment by jjaejjae12** [comment]
구체적으로 어떻게 하면 되나요?

**Comment by chanwoo00106** [comment]
그건 gauth 팀원이랑 상의해야 하지 않을까요?

**Comment by chanwoo00106** [comment]
프로젝트 설명, 사용 방법 같은 걸 적으면 되지 않을까요

**Comment by jjaejjae12** [comment]
작성했습니다. 확인해주세요.

**Comment by chanwoo00106** [comment]
팀원이랑 좀 더 상의 해서 자성하는 것도 좋을 것 같아요
