### ISSUE TITLE
로그인 화면 오타

### ISSUE THREAD

**Issue by googoo81** [GSM-MSG/GAUTH-frontend#79]
회원가입 메세지에 오타가 있습니다. (Guath라고 쓰여있습니다)
![image](https://user-images.githubusercontent.com/101445027/224190372-972d69e2-7a65-4ce6-aaff-4daa7ef68220.png)

**Comment by kangkong0805** [comment]
👍🏻

**Comment by kangkong0805** [comment]
merge 되었습니다
